version: '2'
services:

  db:
    container_name: db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      #Alla creazione del container vengono eseguiti tutti gli script contenuti nella cartella in ordine alfabetico
      - ./mariadb-docker/db-entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: tommaso
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:

  tomcat:
    depends_on:
      - db
    container_name: tomcat
    build:
      context: tomcat-docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ../target:/usr/local/tomcat/webapps
      - ../data:/data
      - ./tomcat-docker/conf:/usr/local/tomcat/conf
