package com.pavastudios.TomMaso.chat;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChatTestingTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void chatTest() {
        driver.get("http://localhost:8080/TomMaso_war_exploded/");
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.id("navbarSearchText")).click();
        driver.findElement(By.id("navbarSearchText")).sendKeys("provaaaa");
        driver.findElement(By.id("navbarSearchText")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".btn-outline-success")).click();
        driver.findElement(By.id("messaggio")).click();
        driver.findElement(By.id("messaggio")).sendKeys("ciao");
        driver.findElement(By.id("invia")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("#m-12 .card-body"));
            assert(elements.size() > 0);
        }
        {
            WebElement element = driver.findElement(By.id("invia"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("messaggio")).click();
        driver.findElement(By.id("messaggio")).sendKeys("DEVE-ESSERE_VUOTO");
        driver.findElement(By.id("messaggio")).click();
        driver.findElement(By.id("invia")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("#m-13 .msg-date"));
            assert(elements.size() == 0);
        }
    }
}
