package com.pavastudios.TomMaso.selenium;

// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class UC7EditMarkDownFileTest extends SeleniumTest{

    @BeforeAll
    public static void setUp() {
        Utility.login(driver, "admin", "admin");
    }

    @Test
    public void uC7EditMarkDownFileTC1() {
        driver.get("http://localhost:8080/TomMaso_war_exploded/blog-manage/llllllllllllll");
        driver.manage().window().setSize(new Dimension(1536, 816));
        driver.findElement(By.cssSelector(".fa-plus > path")).click();
        driver.findElement(By.id("titleMD")).click();
        driver.findElement(By.id("titleMD")).sendKeys("blogtest1");
        driver.findElement(By.cssSelector("#createMD .btn")).click();
        driver.findElement(By.cssSelector("div > textarea")).sendKeys("asdasdasdasdasdasdasdasdasdasdasdasd");
        driver.findElement(By.id("save")).click();
        Assertions.assertEquals("blogtest1.md", driver.getTitle());
    }
}
