package com.pavastudios.TomMaso.selenium;

// Generated by Selenium IDE
import org.testng.annotations.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UploadFileTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void uC6UploadFileFilePresente() {
        driver.get("http://localhost:8080/TomMaso_war_exploded//TomMaso_war_exploded/");
        driver.manage().window().setSize(new Dimension(1536, 816));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username-login")).click();
        driver.findElement(By.id("username-login")).sendKeys("admin");
        driver.findElement(By.id("password-login")).sendKeys("admin");
        driver.findElement(By.id("navbarLoginSubmit")).click();
        driver.findElement(By.cssSelector("path:nth-child(3)")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.cssSelector(".carta:nth-child(2) .code-anim")).click();
        driver.findElement(By.cssSelector(".fa-plus")).click();
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();
        driver.findElement(By.id("file")).click();
        driver.findElement(By.id("file")).sendKeys("C:\\Users\\anton\\OneDrive\\Immagini\\imaginiacaso\\auguri.jpg");
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();
        driver.findElement(By.cssSelector(".add-file .card-body")).click();
        driver.findElement(By.id("file")).click();
        driver.findElement(By.id("file")).sendKeys("C:\\Users\\anton\\OneDrive\\Immagini\\imaginiacaso\\auguri.jpg");
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col-lg-3:nth-child(2)"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".delete-anim")).click();
        driver.findElement(By.id("deleteBlog")).click();
        driver.findElement(By.id("dropdownUser2")).click();
        driver.findElement(By.linkText("Logout")).click();
    }
    @Test
    public void uC6UploadFileFileNonPresente() {
        driver.get("http://localhost:8080/TomMaso_war_exploded/");
        driver.manage().window().setSize(new Dimension(1536, 816));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username-login")).click();
        driver.findElement(By.id("username-login")).sendKeys("admin");
        driver.findElement(By.id("password-login")).click();
        driver.findElement(By.id("password-login")).sendKeys("admin");
        driver.findElement(By.id("navbarLoginSubmit")).click();
        driver.findElement(By.id("nav-svg-user")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.cssSelector(".carta:nth-child(2) .code-anim")).click();
        driver.findElement(By.cssSelector(".fa-plus")).click();
        driver.findElement(By.id("file")).click();
        driver.findElement(By.id("file")).sendKeys("C:\\Users\\anton\\OneDrive\\Immagini\\imaginiacaso\\auguri.jpg");
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col-lg-3:nth-child(2)"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".delete-anim")).click();
        driver.findElement(By.id("deleteBlog")).click();
        driver.findElement(By.cssSelector("path:nth-child(3)")).click();
        driver.findElement(By.linkText("Logout")).click();
    }
}