package com.pavastudios.TomMaso.selenium;

// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class UploadFileTest {
    static JavascriptExecutor js;
    private static WebDriver driver;

    @BeforeAll
    public static void setUp() {
        System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver");
        System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        Utility.login(driver, "admin", "admin");
    }

    @AfterAll
    public static void tearDown() {
        driver.quit();
    }

    private static void wait(By selector) {
        new WebDriverWait(driver, 2).until(ExpectedConditions.visibilityOf(driver.findElement(selector)));
    }

    private static void waitPresence(By selector) {
        new WebDriverWait(driver, 2).until(ExpectedConditions.presenceOfElementLocated(selector));
    }

    @Test
    public void uC6UploadFileFilePresente() {
        driver.get("http://localhost:8080/TomMaso_war_exploded/blog-manage/llllllllllllll");
        driver.findElement(By.cssSelector(".fa-plus")).click();
        wait(By.id("file"));
        driver.findElement(By.id("file")).sendKeys("/home/dar9586/Programmazione/Progetti/Java/TomMaso/selenium/prova.txt");
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();

        driver.findElement(By.cssSelector(".fa-plus")).click();
        wait(By.id("file"));
        driver.findElement(By.id("file")).sendKeys("/home/dar9586/Programmazione/Progetti/Java/TomMaso/selenium/prova.txt");
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();

        driver.findElement(By.cssSelector(".col-6:nth-child(1) > .delete-anim")).click();
        driver.findElement(By.id("deleteBlog")).click();
    }


    @Test
    public void uC6UploadFileFileNonPresente() {
        driver.get("http://localhost:8080/TomMaso_war_exploded/blog-manage/llllllllllllll");
        driver.findElement(By.cssSelector(".fa-plus")).click();
        wait(By.id("file"));
        driver.findElement(By.id("file")).sendKeys("/home/dar9586/Programmazione/Progetti/Java/TomMaso/selenium/prova.txt");
        driver.findElement(By.cssSelector("fieldset:nth-child(1) .btn")).click();

        driver.findElement(By.cssSelector(".col-6:nth-child(1) > .delete-anim")).click();
        driver.findElement(By.id("deleteBlog")).click();
    }
}