// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uC2TC1() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("username-login")).click();
    driver.findElement(By.id("username-login")).sendKeys("a.allocca");
    driver.findElement(By.id("password-login")).click();
    driver.findElement(By.id("password-login")).sendKeys("Allocca123");
    driver.findElement(By.id("navbarLoginSubmit")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("nav-svg-user")));
    }
  }
  @Test
  public void uC2TC2() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("username-login")).click();
    driver.findElement(By.id("username-login")).sendKeys("a.allocca");
    driver.findElement(By.id("password-login")).click();
    driver.findElement(By.id("password-login")).sendKeys("DiCostanzo321");
    driver.findElement(By.id("navbarLoginSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarLogin .modal-error")).getText(), is("Impossibile eseguire login!"));
  }
  @Test
  public void uC2TC3() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("username-login")).click();
    driver.findElement(By.id("username-login")).sendKeys("a.delucia");
    driver.findElement(By.id("password-login")).click();
    driver.findElement(By.id("password-login")).sendKeys("AAAAAAAAA");
    driver.findElement(By.id("navbarLoginSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarLogin .modal-error")).getText(), is("Impossibile eseguire login!"));
  }
  @Test
  public void uC2TC4() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("username-login")).click();
    driver.findElement(By.id("username-login")).sendKeys("utenteBannato");
    driver.findElement(By.id("password-login")).click();
    driver.findElement(By.id("password-login")).sendKeys("bannato12");
    driver.findElement(By.id("navbarLoginSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarLogin .modal-error")).getText(), is("Impossibile eseguire login!"));
  }
}
