// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uC21TC1() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1287, 738));
    driver.findElement(By.id("navbarSearchText")).click();
    driver.findElement(By.id("navbarSearchText")).click();
    driver.findElement(By.id("navbarSearchText")).click();
    {
      WebElement element = driver.findElement(By.id("navbarSearchText"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("navbarSearchText")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-10"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".flex-lg-row-reverse"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("navbarSearchText")).click();
    driver.findElement(By.id("navbarSearchText")).sendKeys("CCCCCCCC");
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    assertThat(driver.getTitle(), is("Errore - TomMASO"));
  }
  @Test
  public void uC21TC2() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.id("navbarSearchText")).click();
    driver.findElement(By.id("navbarSearchText")).sendKeys("DDDDDDDD");
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    assertThat(driver.getTitle(), is("TomMASO - Profilo di DDDDDDDD"));
  }
  @Test
  public void uC21TC3() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1287, 738));
    driver.findElement(By.id("navbarSearchType")).click();
    driver.findElement(By.id("navbarSearchBlog")).click();
    driver.findElement(By.id("navbarSearchText")).click();
    driver.findElement(By.id("navbarSearchText")).sendKeys("AAAAAAAA");
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    assertThat(driver.getTitle(), is("Errore - TomMASO"));
  }
  @Test
  public void uC21TC4() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1287, 738));
    driver.findElement(By.id("navbarSearchType")).click();
    driver.findElement(By.id("navbarSearchBlog")).click();
    driver.findElement(By.id("navbarSearchText")).click();
    driver.findElement(By.id("navbarSearchText")).sendKeys("DDDDDDDD");
    driver.findElement(By.id("navbarSearchText")).sendKeys("BBBBBBBB");
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    assertThat(driver.getTitle(), is("Ultimi post - BBBBBBBB"));
  }
}
