// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SendCommentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uC12TC1() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/blogs/BBBBBBBB/Prima.md");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("testingiswonderful");
    driver.findElement(By.cssSelector(".row:nth-child(3)")).click();
    driver.findElement(By.id("sendComment")).click();
  }
  @Test
  public void uC12TC2() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/blogs/BBBBBBBB/Prima.md");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("ab");
    driver.findElement(By.cssSelector(".row:nth-child(3)")).click();
    driver.findElement(By.id("sendComment")).click();
    assertThat(driver.findElement(By.id("error")).getText(), is("Commento invalido"));
  }
}
