// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UserSignUpTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uC1TC5() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1042, 639));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username-register")).click();
    driver.findElement(By.id("username-register")).sendKeys("XXXXXXXX");
    driver.findElement(By.id("password1-register")).click();
    driver.findElement(By.id("password1-register")).sendKeys("BBBBBBBBB");
    driver.findElement(By.id("formNavbarRegister")).click();
    driver.findElement(By.id("password2-register")).click();
    driver.findElement(By.id("password2-register")).sendKeys("BBBBBBBB");
    driver.findElement(By.id("navbarRegisterSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarRegister .modal-error")).getText(), is("Le password non corrispondono"));
  }
  @Test
  public void uC1TC2() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1042, 639));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username-register")).click();
    driver.findElement(By.id("username-register")).sendKeys("AAAAAAA!");
    driver.findElement(By.id("password1-register")).click();
    driver.findElement(By.id("password1-register")).sendKeys("BBBBBBBB");
    driver.findElement(By.id("formNavbarRegister")).click();
    driver.findElement(By.id("password2-register")).click();
    driver.findElement(By.id("password2-register")).sendKeys("BBBBBBBB");
    driver.findElement(By.id("navbarRegisterSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarRegister .modal-error")).getText(), is("L\\\'username non è valido!"));
  }
  @Test
  public void uC1TC3() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1042, 639));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username-register")).click();
    driver.findElement(By.id("username-register")).sendKeys("AAAAAAAA");
    driver.findElement(By.id("password1-register")).click();
    driver.findElement(By.id("password1-register")).sendKeys("BBBBBBBB");
    driver.findElement(By.id("formNavbarRegister")).click();
    driver.findElement(By.id("password2-register")).click();
    driver.findElement(By.id("password2-register")).sendKeys("BBBBBBBB");
    driver.findElement(By.id("navbarRegisterSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarRegister .modal-error")).getText(), is("Impossibile registrare l\\\'account"));
  }
  @Test
  public void uC1TC4() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1042, 639));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username-register")).click();
    driver.findElement(By.id("username-register")).sendKeys("XXXXXXX");
    driver.findElement(By.id("password1-register")).click();
    driver.findElement(By.id("password1-register")).sendKeys("BBBBBBB");
    driver.findElement(By.id("formNavbarRegister")).click();
    driver.findElement(By.id("password2-register")).click();
    driver.findElement(By.id("password2-register")).sendKeys("BBBBBBB");
    driver.findElement(By.id("navbarRegisterSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarRegister .modal-error")).getText(), is("La password deve contenere almeno 8 caratteri"));
  }
  @Test
  public void uC1TC1() {
    driver.get("http://localhost:8080/TomMaso_war_exploded/");
    driver.manage().window().setSize(new Dimension(1042, 639));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username-register")).click();
    driver.findElement(By.id("username-register")).sendKeys("AAAAAAAA");
    driver.findElement(By.id("password1-register")).click();
    driver.findElement(By.id("password1-register")).sendKeys("BBBBBBBBB");
    driver.findElement(By.id("formNavbarRegister")).click();
    driver.findElement(By.id("password2-register")).click();
    driver.findElement(By.id("password2-register")).sendKeys("BBBBBBBBB");
    driver.findElement(By.id("navbarRegisterSubmit")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("nav-svg-user")));
    }
  }
}
